[INFO  2019-10-23 16:17:54 @__init__.py:79] Set root logger. Unset logger with neuralgym.unset_logger().
[INFO  2019-10-23 16:17:54 @__init__.py:80] Saving logging to file: neuralgym_logs/20191023161754718617.
[INFO  2019-10-23 16:17:55 @_internal.py:122]  * Running on http://172.19.140.150:5003/ (Press CTRL+C to quit)
[INFO  2019-10-23 16:17:59 @driver.py:230] init
[DEBUG 2019-10-23 16:17:59 @driver.py:292] call driver api: cuInit
[DEBUG 2019-10-23 16:17:59 @driver.py:292] call driver api: cuDeviceGetCount
[DEBUG 2019-10-23 16:17:59 @driver.py:292] call driver api: cuDeviceGet
[DEBUG 2019-10-23 16:17:59 @driver.py:292] call driver api: cuDeviceComputeCapability
[DEBUG 2019-10-23 16:17:59 @driver.py:292] call driver api: cuDeviceGetName
[DEBUG 2019-10-23 16:17:59 @driver.py:292] call driver api: cuDevicePrimaryCtxRetain
[DEBUG 2019-10-23 16:17:59 @driver.py:292] call driver api: cuCtxPushCurrent_v2
[DEBUG 2019-10-23 16:17:59 @driver.py:292] call driver api: cuMemGetInfo_v2
[INFO  2019-10-23 16:17:59 @_internal.py:122] 172.19.140.253 - - [23/Oct/2019 16:17:59] "[37mPOST /inpainting/api/v1.0/order HTTP/1.1[0m" 200 -
[ERROR 2019-10-23 16:18:16 @app.py:1891] Exception on /inpainting/api/v1.0/order/storage/9fa1b984-f56d-11e9-81b3-00e02b680747 [DELETE]
Traceback (most recent call last):
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api.py", line 118, in img_delete
    id = ImgDB.query.get(uuid.id)
AttributeError: 'NoneType' object has no attribute 'id'
[INFO  2019-10-23 16:18:16 @_internal.py:122] 172.19.140.253 - - [23/Oct/2019 16:18:16] "[1m[35mDELETE /inpainting/api/v1.0/order/storage/9fa1b984-f56d-11e9-81b3-00e02b680747 HTTP/1.1[0m" 500 -
