[INFO  2019-10-21 16:06:04 @__init__.py:79] Set root logger. Unset logger with neuralgym.unset_logger().
[INFO  2019-10-21 16:06:04 @__init__.py:80] Saving logging to file: neuralgym_logs/20191021160604465399.
[INFO  2019-10-21 16:06:05 @_internal.py:122]  * Running on http://172.19.140.150:5003/ (Press CTRL+C to quit)
[INFO  2019-10-21 16:06:07 @_internal.py:122] 172.19.140.253 - - [21/Oct/2019 16:06:07] "[37mPOST /inpainting/api/v1.0/order HTTP/1.1[0m" 200 -
[ERROR 2019-10-21 16:06:35 @app.py:1891] Exception on /inpainting/api/v1.0/order [POST]
Traceback (most recent call last):
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[INFO  2019-10-21 16:06:35 @_internal.py:122] 172.19.140.253 - - [21/Oct/2019 16:06:35] "[1m[35mPOST /inpainting/api/v1.0/order HTTP/1.1[0m" 500 -
