[INFO  2019-10-23 17:04:23 @__init__.py:79] Set root logger. Unset logger with neuralgym.unset_logger().
[INFO  2019-10-23 17:04:23 @__init__.py:80] Saving logging to file: neuralgym_logs/20191023170423283691.
[INFO  2019-10-23 17:04:24 @_internal.py:122]  * Running on http://172.19.140.150:5003/ (Press CTRL+C to quit)
[ERROR 2019-10-23 17:04:26 @app.py:1891] Exception on /inpainting/api/v1.0/order/e2bf9592-f572-11e9-bee7-00e02b680747 [GET]
Traceback (most recent call last):
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api.py", line 105, in img_detail
    return jsonify(uuid.imgbase64)
AttributeError: 'NoneType' object has no attribute 'imgbase64'
[INFO  2019-10-23 17:04:26 @_internal.py:122] 172.19.140.253 - - [23/Oct/2019 17:04:26] "[1m[35mGET /inpainting/api/v1.0/order/e2bf9592-f572-11e9-bee7-00e02b680747 HTTP/1.1[0m" 500 -
[ERROR 2019-10-23 17:04:31 @app.py:1891] Exception on /inpainting/api/v1.0/order/e2bf9592-f572-11e9-bee7-00e02b680747 [GET]
Traceback (most recent call last):
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api.py", line 105, in img_detail
    return jsonify(uuid.imgbase64)
AttributeError: 'NoneType' object has no attribute 'imgbase64'
[INFO  2019-10-23 17:04:31 @_internal.py:122] 172.19.140.253 - - [23/Oct/2019 17:04:31] "[1m[35mGET /inpainting/api/v1.0/order/e2bf9592-f572-11e9-bee7-00e02b680747 HTTP/1.1[0m" 500 -
[INFO  2019-10-23 17:04:44 @_internal.py:122] 172.19.140.253 - - [23/Oct/2019 17:04:44] "[37mPOST /inpainting/api/v1.0/order HTTP/1.1[0m" 200 -
