[INFO  2019-10-23 11:08:02 @__init__.py:79] Set root logger. Unset logger with neuralgym.unset_logger().
[INFO  2019-10-23 11:08:02 @__init__.py:80] Saving logging to file: neuralgym_logs/20191023110802935143.
[INFO  2019-10-23 11:08:03 @_internal.py:122]  * Running on http://172.19.140.150:5003/ (Press CTRL+C to quit)
[ERROR 2019-10-23 11:09:13 @app.py:1891] Exception on /inpainting/api/v1.0/order/0b7f7f96-f542-11e9-a45b-00e02b680747 [GET]
Traceback (most recent call last):
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api.py", line 95, in img_detail
    return jsonify(uuid.imgbase64)
AttributeError: 'NoneType' object has no attribute 'imgbase64'
[INFO  2019-10-23 11:09:13 @_internal.py:122] 172.19.140.253 - - [23/Oct/2019 11:09:13] "[1m[35mGET /inpainting/api/v1.0/order/0b7f7f96-f542-11e9-a45b-00e02b680747 HTTP/1.1[0m" 500 -
[INFO  2019-10-23 11:09:20 @_internal.py:122] 172.19.140.253 - - [23/Oct/2019 11:09:20] "[37mPOST /inpainting/api/v1.0/order HTTP/1.1[0m" 200 -
[INFO  2019-10-23 11:10:09 @_internal.py:122] 172.19.140.253 - - [23/Oct/2019 11:10:09] "[37mPOST /inpainting/api/v1.0/order HTTP/1.1[0m" 200 -
